# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

version: '3'
services:
  bridge:
    user: "${UID}:${GID}"
    build:
      context: .
    container_name: bridge
    environment:
      - KEYSTORE_PASSWORD=12345678
    command: --config /config/config.json --keystore /keys --verbosity trce
    volumes:
      - ./config:/config
      - ./keys:/keys/
    network_mode: host