
[[chains]]
id = 0
endpoint = "ws://192.168.0.13:8545"
emitter = "0x1fA38b0EfccA4228EB9e15112D4d98B0CEe3c600"
receiver = "0x290f41e61374c715C1127974bf08a3993afd0145"
from = "02855e96adad26f99329dd921889fbf94811b0de26efeb8b251b9e1f83f02d8597"


[[chains]]
id = 1
endpoint = "ws://192.168.0.13:8546"
emitter = "0x1fA38b0EfccA4228EB9e15112D4d98B0CEe3c600"
receiver = "0x290f41e61374c715C1127974bf08a3993afd0145"
from = "02855e96adad26f99329dd921889fbf94811b0de26efeb8b251b9e1f83f02d8597"
