# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

site_name: ChainBridge documentation
site_description: Modular Multi-Directional Blockchain Bridge to interact with Multiple Networks; Ethereum, Ethereum Classic, Substrate, Cosmos-SDK based chains.

repo_name: chainsafe/chainbridge
repo_url: https://github.com/ChainSafe/chainbridge

# Configuration
markdown_extensions:
  - meta
  - admonition
  - codehilite
  - toc:
      permalink: true

theme:
  name: material
  palette:
    primary: black
  favicon: img/favicon.ico
nav:
  - Getting started: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Chains:
      - Ethereum: chains/ethereum.md
      - Substrate: chains/substrate.md
  - Testing: test.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ChainSafe/ChainBridge
